from keybench.main.component.implementation.candidate_extractor.n_gram_extractor import NGramExtractor
from keybench.main.component.implementation.candidate_extractor.pos_sequence_based_candidate_extractor import POSSequenceBasedCandidateExtractor

